### PR TITLE
Get updated data

### PR DESCRIPTION
**Pull request by delwen**
@maia-sh I started implementing the changes to pull in the updated data from the intovalue-data repo. I changed the URLs in the first script, but realised I may need some additional files (e.g., cross registration). Could you take over from here and re-run all the scripts? Then we can merge into main and we'll have our final dataset moving forward. Thanks!

### CODE REVIEW

**Comment by maia-sh** [comment]
are you out of the branch? i can then just check it out

**Comment by maia-sh** [comment]
hi! i just checked and you should be able to run it because the files you need are all on remote. can you give it a try? if not, i will make changes on iv, since we need that for reproducibility

**Comment by delwen** [comment]
Hi! Yes, so I made the necessary changes to the first script (i.e., get data from `update-2022-april` branch) and can re-run. No changes needed to the second script and can re-run. I just ran into issues with the third script `check-euctr-crossreg.R` (no PDFs) but perhaps not necessary? Finally, should be no problem to rerun the last `prep-contacts.R` script.

Just let me know if anything is not needed, and I'll give it another go!

**Comment by maia-sh** [comment]
no need to run the check euctr script. i don't think you need to rerun contacts prep either, at least not for the report cards.

**Comment by delwen** [comment]
Thanks, and done! Just reran the first 2 scripts. Shall we merge into main?

**Pull request merged**
